### ISSUE TITLE
[BUG] Spotify Logging Out On Its Own While Using Extension

### ISSUE THREAD

**Issue by svvedishfish** [jackweatherford/spotify-friend-activity#1]
The Bug:
After a while of using the browser version of Spotify with the extension enabled, Spotify will log out of the account occasionally. It's happened three times within the last couple of days (sorry I don't have specific times!) and while it isn't an urgent problem, I wanted to make a report regardless to note that it was happening. Before using this extension, Spotify would only log out on it's own about once a month or less. I'm not being prevented from logging back in, but the logging out can be obnoxious, especially if I'm in the middle of making a playlist, etc. Other than that, the extension is working perfectly and I've had no other problems! :)

Error Reproduction:
1. Use Spotify as normal and wait for it to happen.
2. Spotify logs out on it's own in the middle of activity.

System Info:
- Operating System: latest version of windows
- Screen Resolution: 1920x1080
- Chrome Version: I'm using this extension on the Opera GX browser (version: LVL3 (core: 85.0.4341.72)) through Opera's "install chrome extensions" feature

Additional Context:
I'm also using uBlock Origin and I have Opera GX's "block ads" and "block trackers" functions enabled. I'm not sure if those may be a part of the problem, though they've never interfered with any other extensions.

**Comment by jackweatherford** [comment]
I tried using the extension on Opera GX for a few hours and I haven't been able to reproduce this behavior.

The fact that the bug was happening to you before using the extension suggests that the root cause may be unrelated to the extension - though the extension may be worsening the issue.

It may be the result of be an automatic system cleaning app. Opera GX's "GX Control" might be running a RAM/CPU Limiter that's cleaning your data, similarly "GX Cleaner" might be running automatically and cleaning your data - look into these to see if they're the culprit.
